### ISSUE TITLE
Replace apt-get with apt

### ISSUE THREAD

**Issue by gavr123456789** [hannesschulze/optimizer#38]
```
 if (Environment.find_program_in_path ("apt") != null) {
                return { "/var/cache/apt/archives", "deb" };
            }
            if (Environment.find_program_in_path ("pacman") != null) {
                return { "/var/cache/pacman/pkg", "xz" };
            }
```
apt-get is deprecated, use just apt.

I would recommend using a clean with a native package manager rather than a manual one. 
For example, using spawn_command_line_async ()
Here is a list of commands for dnf  https://dnf.readthedocs.io/en/latest/command_ref.html#clean-command-label

**Comment by tim77** [comment]
In Fedora package cache stored in `/var/cache/dnf` and `/var/cache/PackageKit/`. Just FYI.

**Comment by hannesschulze** [comment]
apt-get isn't really deprecated. `apt` just provides a more user-friendly interface while apt-get is just for accessing the backend (as far as I know). Apt-get isn't going to be removed anytime soon from what I've read and it is still common to use it in scripts.

For the commands: I'm currently deleting the files with rm because I can get the exact size of the files that will be deleted. I don't know how to do that with the commands and I think that would be a little bit too complicated. Maybe I could add that as a fallback later (just showing something like "could not be calculated").

@tim77 I installed fedora a few days ago. On my system, /var/cache/dnf contains some folders and .solvx files. Is it save to just delete all of them?

**Comment by tim77** [comment]
> @tim77 I installed fedora a few days ago. On my system, /var/cache/dnf contains some folders and .solvx files. Is it save to just delete all of them?

Some people says its safe to delete but some reporting about problems after clearing mannualy this folders. IMO better do for PackageKit:
`sudo pkcon refresh force`
For DNF:
`sudo dnf clean all`

Ill ask about this DNF devs and tell you...

**Comment by tim77** [comment]
@hannesschulze yes, you can safely clean up this folders.

Source: DNF devs.

**Comment by hannesschulze** [comment]
Ok, thanks :) I'll implement that then
