### ISSUE TITLE
Suggestions for a better Dashboard UI

### ISSUE THREAD

**Issue by Fatih20** [hannesschulze/optimizer#82]
The current front dashboard IMO is not really a good UI and feels too utilitarian or "programmer design" (no offense). 
![Screenshot from 2020-01-26 09 12 46](https://user-images.githubusercontent.com/51940383/77842224-03cf6280-71ba-11ea-9bf2-889ffba6a246.png)
As such, I have a suggestion for a better one.
![O Sketch](https://user-images.githubusercontent.com/51940383/77842228-08941680-71ba-11ea-9867-0c2f83e92d4a.png)

If you wanted to move forward with this, I'll make the elementary-esque icon for the CPU.

**Comment by hannesschulze** [comment]
Hey there,

Thanks for opening this issue. I'm usually a big fan of making things more symbolic and understandable. However, I don't think it fits well in this particular case because of the following reasons:

- Showing Information for the system isn't the main view's primary task — that is to show the current usage. If I were to increase the space the main view uses, both would seem equally weighed. If you want to see your system information nicely displayed, there's already the system settings About section. I'm not going to copy that.
- From a design standpoint, it feels like this layout is a bit cluttered since the window size is pretty small. Again, I don't want to change that because Optimizer should only be a "small" tool you can just open up and not a big dashboard where you have to look for the widget you want.
- (Just my two cents) I think the icons in your proposal are a bit too big compared to the amount of text.

You're right about this layout being confusing and I will make a small improvement to it by splitting the text up into two labels for the next release (similar to GNOME's about section), however this specific proposal isn't something I want to implement.

All in all I think we both have different goals for our designs so I will close this issue for now.

**Comment by Fatih20** [comment]
You're right, but if this is true,
> Showing Information for the system isn't the main view's primary task
then don't bother having them at all. Better to not have it at all rather than have it but not doing it right.
